baseURL: "https://carreteroc.me/"
title: willow carretero chavez 
paginate: 5
theme: PaperMod

enableRobotsTXT: true

params:
  title: willow carretero chavez
  description: "willow carretero chavez's personal website"
  author: Willow Carretero Chavez
  DateFormat: "January 2, 2006"
  defaultTheme: dark # dark, light

  assets:
    favicon: "/img/favicon.ico"
    favicon16x16: "/img/favicon-16x16.png"
    favicon32x32: "/img/favicon-32x32.png"

  profileMode:
    enabled: true
    title: willow carretero chavez
    subtitle: "biologist | software engineer | nerd"
    imageUrl: "/img/avatar.png"
    imageTitle: willow

  socialIcons:
    - name: github
      url: "https://github.com/carreter"
    - name: linkedin
      url: "https://www.linkedin.com/in/wcarretero/"

taxonomies:
  series: series
  tags: tags
  categories: categories

menu:
  main:
    - identifier: posts
      name: posts
      url: /posts/
      weight: 1
    - identifier: categories
      name: categories
      url: /categories/
      weight: 10
    - identifier: series
      name: series
      url: /series/
      weight: 15
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
    - identifier: resume
      name: resume
      url: /resume.pdf
      weight: 30

